-- SCRIPT DE REFATORIZAÇÃO: COMPETÊNCIAS M:N
-- Objetivo: Separar Competências em Catálogo e Associação com Módulos.
-- Atenção: Isto irá APAGAR dados existentes na tabela Competencias antiga.

-- 1. Apagar tabela antiga (1:N)
DROP TABLE Competencias CASCADE CONSTRAINTS;

-- 2. Criar tabela de Catálogo (Sem ID_Modulo)
CREATE TABLE Catalogo_Competencias (
    ID_Competencia NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nome VARCHAR2(255) NOT NULL,
    Descricao VARCHAR2(4000),
    ID_Area_Competencia NUMBER,
    ID_Nivel_Proficiencia NUMBER,
    URL_Medalha_Digital VARCHAR2(500),
    URL_Icone_Badge VARCHAR2(500),
    URL_Claim_Badge VARCHAR2(500),
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S','N'))
);

-- 3. Criar tabela de Associação (M:N)
CREATE TABLE Modulo_Competencias (
    ID_Associacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Modulo NUMBER NOT NULL,
    ID_Competencia NUMBER NOT NULL,
    Obrigatorio CHAR(1) DEFAULT 'S' CHECK (Obrigatorio IN ('S','N')),
    CONSTRAINT FK_ModCom_Modulo FOREIGN KEY (ID_Modulo) REFERENCES Modulos(ID_Modulo) ON DELETE CASCADE,
    CONSTRAINT FK_ModCom_Competencia FOREIGN KEY (ID_Competencia) REFERENCES Catalogo_Competencias(ID_Competencia) ON DELETE CASCADE,
    CONSTRAINT UK_ModCom_Unique UNIQUE (ID_Modulo, ID_Competencia)
);

-- 4. Adicionar FKs para Lookups (Se existirem)
-- Ajuste conforme necessário se os nomes das tabelas de lookup forem diferentes
-- ALTER TABLE Catalogo_Competencias ADD CONSTRAINT FK_CatCom_Area FOREIGN KEY (ID_Area_Competencia) REFERENCES Tipos_Area_Competencia(ID_Area_Competencia);
-- ALTER TABLE Catalogo_Competencias ADD CONSTRAINT FK_CatCom_Nivel FOREIGN KEY (ID_Nivel_Proficiencia) REFERENCES Tipos_Nivel_Proficiencia(ID_Nivel_Proficiencia);

DESC Catalogo_Competencias;
DESC Modulo_Competencias;
