-- 02_Refactor_Medalhas_MN.sql
-- Objetivo: Separar Medalhas das Competências (Relacionamento M:N)
-- Data: 2026-01-20

-- 1. Criar Tabela: Catálogo de Medalhas (Open Badges)
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE Catalogo_Medalhas (
        ID_Medalha NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        Nome VARCHAR2(255) NOT NULL,
        Descricao VARCHAR2(4000),
        URL_Medalha_Digital VARCHAR2(500),
        URL_Imagem VARCHAR2(500),
        URL_Claim_Badge VARCHAR2(500),
        Ativo CHAR(1) DEFAULT ''S'' CHECK (Ativo IN (''S'',''N''))
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF; -- Ignora erro se tabela já existe
END;
/

-- 2. Criar Tabela: Associação Competência <-> Medalha (M:N)
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE Competencia_Medalhas (
        ID_Associacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        ID_Competencia NUMBER NOT NULL,
        ID_Medalha NUMBER NOT NULL,
        CONSTRAINT FK_CompMed_Comp FOREIGN KEY (ID_Competencia) REFERENCES Catalogo_Competencias(ID_Competencia) ON DELETE CASCADE,
        CONSTRAINT FK_CompMed_Medalha FOREIGN KEY (ID_Medalha) REFERENCES Catalogo_Medalhas(ID_Medalha) ON DELETE CASCADE
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 3. Criar Tabela: Seleção do Formador (Medalhas Elegíveis por Turma)
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE Turma_Medalhas_Elegiveis (
        ID_Associacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        ID_Turma NUMBER NOT NULL,
        ID_Medalha NUMBER NOT NULL,
        Selecionado_Por VARCHAR2(255),
        Data_Selecao DATE DEFAULT SYSDATE,
        CONSTRAINT FK_TurmaMed_Turma FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma) ON DELETE CASCADE,
        CONSTRAINT FK_TurmaMed_Medalha FOREIGN KEY (ID_Medalha) REFERENCES Catalogo_Medalhas(ID_Medalha) ON DELETE CASCADE
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 4. Migração de Dados (Opcional - Criar Medalhas Genéricas se existirem dados)
-- (Nesta fase de dev, assumimos que podemos limpar ou migrar manualmente)

-- 5. Remover Colunas Antigas de Competências
-- ATENÇÃO: Só executar se tiver a certeza.
BEGIN
    -- Verificar se coluna existe antes de apagar para evitar erros
    FOR i IN (SELECT column_name FROM user_tab_cols WHERE table_name = 'CATALOGO_COMPETENCIAS' AND column_name IN ('URL_MEDALHA_DIGITAL', 'URL_ICONE_BADGE', 'URL_CLAIM_BADGE')) 
    LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE Catalogo_Competencias DROP COLUMN ' || i.column_name;
    END LOOP;
END;
/
