-- 02C_Mailing_Lists.sql
-- Objetivo: Criar estrutura para gestão de Listas de Distribuição (Mailing Lists)
-- Data: 22-Jan-2026

-- 1. Catálogo de Listas de Mailing
CREATE TABLE Listas_Mailing (
    ID_Lista NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nome_Lista VARCHAR2(100) NOT NULL,
    Descricao VARCHAR2(255),
    Ativo CHAR(1) DEFAULT 'S' CHECK (Ativo IN ('S', 'N'))
);

-- Indice unico para nome
CREATE UNIQUE INDEX UK_Listas_Mailing_Nome ON Listas_Mailing(Nome_Lista);

-- 2. Tabela de Associação (M:N) Entidade <-> Lista
CREATE TABLE Entidade_Listas (
    ID_Entidade NUMBER NOT NULL,
    ID_Lista NUMBER NOT NULL,
    Data_Associacao DATE DEFAULT SYSDATE,
    Created_By VARCHAR2(100) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER),
    
    CONSTRAINT PK_Entidade_Listas PRIMARY KEY (ID_Entidade, ID_Lista),
    CONSTRAINT FK_EntListas_Entidade FOREIGN KEY (ID_Entidade) REFERENCES Entidades(ID_Entidade) ON DELETE CASCADE,
    CONSTRAINT FK_EntListas_Lista FOREIGN KEY (ID_Lista) REFERENCES Listas_Mailing(ID_Lista)
);

-- 3. Seed Data (Dados Iniciais)
BEGIN
    INSERT INTO Listas_Mailing (Nome_Lista, Descricao) VALUES ('Vip', 'Personalidades e parceiros estratégicos');
    INSERT INTO Listas_Mailing (Nome_Lista, Descricao) VALUES ('Newsletter Geral', 'Subscritores de novidades gerais');
    INSERT INTO Listas_Mailing (Nome_Lista, Descricao) VALUES ('Antigos Alunos', 'Alumni da Academia Digital');
    INSERT INTO Listas_Mailing (Nome_Lista, Descricao) VALUES ('Potenciais Formadores', 'Interessados em dar formação');
    COMMIT;
END;
/
