-- 04_Operacoes.sql
-- Objetivo: Criar estrutura para Logística e Operações (Turmas, Sessões, Equipa)
-- Data: 22-Jan-2026

-- 1. Locais (Garantir existência)
-- Se a tabela Locais não existir, criar tabela básica.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'LOCAIS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE Locais (
            ID_Local NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            Codigo VARCHAR2(50),
            Nome VARCHAR2(200) NOT NULL,
            Morada VARCHAR2(500),
            Capacidade NUMBER,
            Ativo CHAR(1) DEFAULT ''S''
        )';
    END IF;
END;
/

-- 1.1 Tabela de Tipos de Plano (Lookup #31) - Garantir existência
DECLARE
    v_count NUMBER;
BEGIN
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'TIPOS_PLANO_DDF';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE Tipos_Plano_DDF (
            ID_Tipo_Plano NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            Codigo VARCHAR2(50),
            Descricao VARCHAR2(200) NOT NULL
        )';
        -- Seed Data
        EXECUTE IMMEDIATE 'INSERT INTO Tipos_Plano_DDF (Codigo, Descricao) VALUES (''INTERNA'', ''Formação Interna'')';
        EXECUTE IMMEDIATE 'INSERT INTO Tipos_Plano_DDF (Codigo, Descricao) VALUES (''EXTERNA'', ''Formação Externa'')';
        COMMIT;
    END IF;
END;
/

-- 2. Turmas (A instância do curso)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'TURMAS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE Turmas (
            ID_Turma NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            ID_Curso NUMBER NOT NULL,
            Codigo_Turma VARCHAR2(100) UNIQUE, -- Gerado automaticamente ex: CURSO-ANO-MES
            Nome_Turma VARCHAR2(200),
            ID_Estado_Turma NUMBER,
            Data_Inicio DATE,
            Data_Fim DATE,
            ID_Local NUMBER,
            Horario_Descritivo VARCHAR2(500), -- Texto livre ex: "2ª e 4ª das 18h às 20h"
            ID_Coordenador NUMBER, -- FK para Entidades
            Vagas NUMBER,
            
            -- Dados Admin/SIGO
            Num_Informacao VARCHAR2(100),
            Num_Informacao_Mae VARCHAR2(100),
            Cod_Acao_SIGO VARCHAR2(100),
            ID_Tipo_Plano NUMBER,
            Avaliacao_Ativa CHAR(1) DEFAULT ''S'',
            Observacoes CLOB,
            
            FOREIGN KEY (ID_Curso) REFERENCES Cursos(ID_Curso),
            FOREIGN KEY (ID_Estado_Turma) REFERENCES Tipos_Estado_Turma(ID_Estado_Turma),
            FOREIGN KEY (ID_Local) REFERENCES Locais(ID_Local),
            FOREIGN KEY (ID_Coordenador) REFERENCES Entidades(ID_Entidade),
            FOREIGN KEY (ID_Tipo_Plano) REFERENCES Tipos_Plano_DDF(ID_Tipo_Plano)
        )';
    ELSE
        -- Se já existe, tentar adicionar colunas em falta (ex: ID_Tipo_Plano se versão antiga)
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE Turmas ADD (ID_Tipo_Plano NUMBER, CONSTRAINT FK_Turmas_TipoPlano FOREIGN KEY (ID_Tipo_Plano) REFERENCES Tipos_Plano_DDF(ID_Tipo_Plano))';
        EXCEPTION WHEN OTHERS THEN NULL; -- Coluna já existe
        END;
    END IF;
END;
/

-- 3. Equipa Formativa (Quem dá a turma)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'EQUIPA_FORMATIVA';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE Equipa_Formativa (
            ID_Turma NUMBER,
            ID_Formador NUMBER,
            Principal CHAR(1) DEFAULT ''N'',
            PRIMARY KEY (ID_Turma, ID_Formador),
            FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma),
            FOREIGN KEY (ID_Formador) REFERENCES Entidades(ID_Entidade)
        )';
    END IF;
END;
/

-- 4. Sessões (O Cronograma detalhado)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'SESSOES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE Sessoes (
            ID_Sessao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            ID_Turma NUMBER NOT NULL,
            Nome VARCHAR2(200), -- Ex: "Sessão 1: Introdução"
            Data_Sessao DATE NOT NULL,
            Hora_Inicio VARCHAR2(5), -- HH:MM
            Hora_Fim VARCHAR2(5),    -- HH:MM
            Duracao_Horas NUMBER,
            Sumario CLOB,
            ID_Formador NUMBER, -- Pode variar por sessão
            URL_Recursos VARCHAR2(1000),
            FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma),
            FOREIGN KEY (ID_Formador) REFERENCES Entidades(ID_Entidade)
        )';
    END IF;
END;
/
