-- 06_Pedagogia.sql
-- Capítulo 6: Execução Pedagógica (Refatorado para v7)
-- Este script cria as tabelas necessárias para o dia-a-dia do Formador.

-- 1. Presenças (Assiduidade por Sessão)
-- Regista quem esteve na aula e quantas horas assistiu.
CREATE TABLE Presencas (
    ID_Presenca NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Sessao NUMBER NOT NULL,
    ID_Matricula NUMBER NOT NULL,
    ID_Estado_Presenca NUMBER, -- FK para lookup (opcional)
    Horas_Assistidas NUMBER,
    Data_Registo TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (ID_Sessao) REFERENCES Sessoes(ID_Sessao) ON DELETE CASCADE,
    FOREIGN KEY (ID_Matricula) REFERENCES Matriculas(ID_Matricula) ON DELETE CASCADE
);

-- 2. Avaliações (Notas por Módulo)
-- Regista a nota final e feedback qualitativo de cada módulo.
CREATE TABLE Avaliacoes_Modulo (
    ID_Avaliacao NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Matricula NUMBER NOT NULL,
    ID_Modulo NUMBER NOT NULL,
    Nota_Valor NUMBER,
    Feedback_Texto CLOB,
    Aprovado CHAR(1) CHECK (Aprovado IN ('S', 'N')),
    Data_Avaliacao DATE DEFAULT SYSDATE,
    FOREIGN KEY (ID_Matricula) REFERENCES Matriculas(ID_Matricula) ON DELETE CASCADE,
    FOREIGN KEY (ID_Modulo) REFERENCES Modulos(ID_Modulo) ON DELETE CASCADE
);

-- 3. Badges Conquistados (Histórico do Aluno)
-- Regista que um aluno "ganhou" uma medalha numa determinada turma.
-- Nota: A "eligibilidade" (quais medalhas a turma PODE dar) está na tabela Turma_Medalhas_Elegiveis.
CREATE TABLE Badges_Conquistados (
    ID_Badge_Aluno NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Matricula NUMBER NOT NULL,
    ID_Medalha NUMBER NOT NULL,
    ID_Turma NUMBER NOT NULL,
    Data_Conquista DATE DEFAULT SYSDATE,
    URL_Evidencia VARCHAR2(500), -- Link para prova de trabalho (opcional)
    Token_Validacao VARCHAR2(100), -- Token único se gerado automaticamente
    FOREIGN KEY (ID_Matricula) REFERENCES Matriculas(ID_Matricula) ON DELETE CASCADE,
    FOREIGN KEY (ID_Medalha) REFERENCES Catalogo_Medalhas(ID_Medalha) ON DELETE CASCADE,
    FOREIGN KEY (ID_Turma) REFERENCES Turmas(ID_Turma) ON DELETE CASCADE
);

-- Indexação para Performance (Opcional mas recomendado)
CREATE INDEX IDX_Presencas_Sessao ON Presencas(ID_Sessao);
CREATE INDEX IDX_Avaliacoes_Matricula ON Avaliacoes_Modulo(ID_Matricula);
CREATE INDEX IDX_Badges_Aluno ON Badges_Conquistados(ID_Matricula);
